### ISSUE TITLE
Not getting syntax highlighting for JS sections

### ISSUE THREAD

**Issue by wamoyo** [digitaltoad/vim-pug#108]
Picture's worth 24.5 words:

![screenshot from 2018-11-06 23-21-31](https://user-images.githubusercontent.com/1170326/48110558-d8418600-e21a-11e8-9c34-e165b10986d4.png)

I changed laptops, and moved all my config files over, but of course, some things don't work. This be one of 'em : )

**Comment by wamoyo** [comment]
Gnome Terminal version 3.28.2
`# GNOME Terminal 3.28.2 using VTE 0.52.2 +GNUTLS -PCRE2`

Neovim version: NVIM v0.2.2

**Comment by wamoyo** [comment]
Gnome Terminal version 3.28.2
`# GNOME Terminal 3.28.2 using VTE 0.52.2 +GNUTLS -PCRE2`

Neovim version: NVIM v0.2.2

**Comment by wamoyo** [comment]
Moll's advice form the issue #98 was great. 

Adding `syn region pugJavascriptLine start=/^\s*-/ end=/$/ contains=@htmlJavascript`

Resolved the issue.

Shall I set up a pull request?

**Comment by meloncatty** [comment]
That advice did not resolve this issue for me. After a taking a deep dive into `pug.vim` and the docs I have a bit of a fix. Would like to submit a PR if that's alright.

**Comment by acidjazz** [comment]
@meloncatty can you check out the newly introduced issues this fix added in issue #112  ?
